---
title: "data processing"
author: "Matthew Watts"
date: "2024-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}



library(tidyverse)
library(sf)
library(readxl)

belgium_shp <- st_read("data/postaldistricts.shp")


```

```{r}

Ae_albopictus_distribution <- read_excel("data/Ae_albopictus_2018_2023.xlsx")

```

```{r}

head(belgium_shp)
plot(belgium_shp["nouveau_PO"])

```

```{r}

# Rename post code area

belgium_shp <- dplyr::rename(belgium_shp, Postcode = nouveau_PO)

belgium_shp$Postcode <- as.numeric(belgium_shp$Postcode)


# summarise shapes based on postcodes
belgium_shp <- belgium_shp %>%
  select(Postcode) %>%
  group_by(Postcode) %>%
  summarise() %>%
  ungroup()

# Step 1: Make all geometries valid
belgium_shp <- st_make_valid(belgium_shp)
# Step 2: Remove NA geometries, if any
belgium_shp <- belgium_shp[!is.na(belgium_shp$geometry), ]

# Step 3: Apply a zero-width buffer to clean geometries further
belgium_shp <- st_buffer(belgium_shp, 0.0)

```



```{r}

# load up different scales of data to create different spatial levels

districts_shp <- st_read("data/arrondissement_4326.shp") 

municipality <- st_read("data/municipality_4326.shp") 

# Assuming 'municipality' is your sf object with polygons
municipality <- st_zm(municipality)

# Calculate centroids of the polygons
post_code_centroids <- st_centroid(belgium_shp)


ggplot() +
  geom_sf(data = municipality, fill = "lightblue", color = "darkblue") +  # Draw polygons
  geom_sf(data = post_code_centroids, color = "red", size = .1)  # Draw points


library(sf)

# Ensure both datasets have the same CRS
crs_municipality <- st_crs(municipality)


# Perform the spatial join
joined_data <- st_join(municipality, post_code_centroids, join = st_intersects)

# View the first few rows of the joined data
head(joined_data)

# Drop the geometry and create a new non-spatial dataframe
municipality_post_code_link <- st_drop_geometry(joined_data)

municipality_post_code_link <- dplyr::select(municipality_post_code_link, niscode,  nameger,    namefre,    namedut,    Postcode)

```

```{r}

# Reshape the dataset, get all the observation years in the dataset

# Extracting the column names as a vector
column_names <- names(Ae_albopictus_distribution)

# This will return a logical vector where TRUE represents a numeric value
is_numeric <- grepl("^[0-9]+$", column_names)

# Filter the vector to get only numeric entries
columns_to_transform <- column_names[is_numeric]


# Edit data frame so that only positive year are included instead of months


# Function to apply the required transformation, using 'Status' column for replacement
transform_values <- function(x) {
  if_else(is.na(x) | x == 0, 0, 1)
}

# Old function 
# Function to apply the required transformation, using 'Status' column for replacement
#transform_values <- function(x, Status) {
#  if_else(is.na(x) | x == 0, "not reported", as.character(Status))
#}


# Apply the transformation using 'mutate' and 'across'
Ae_albopictus_distribution <- Ae_albopictus_distribution %>%
  mutate(across(all_of(columns_to_transform), 
                ~transform_values(.x)))  # Naming the new columns with a suffix to differentiate

```

```{r}

# First merge the two columns so years & presence are in a row.  

# Transform data from wide to long format
long_aedes_data <- Ae_albopictus_distribution %>%
  pivot_longer(
    cols = all_of(columns_to_transform),         # Specify the columns to pivot (excluding 'id')
    names_to = "year",  # Name of the new column for the years
    values_to = "detection" # Name of the new column for the presence values
  )



```


```{r}

# Create a new date column
long_aedes_data$Detection_date <- ymd(paste(long_aedes_data$year, long_aedes_data$detection, "01", sep = "-"))

long_aedes_data <- dplyr::filter(long_aedes_data, !is.na(Detection_date))



```

```{r}
### Generate unique ID

# Function to keep only digits
keep_digits <- function(x) {
  gsub("[^0-9]", "", x)
}

# Concatenate columns and remove non-digit characters
long_aedes_data$ID <- paste(long_aedes_data$Latitude, long_aedes_data$Longitude, long_aedes_data$Detection_date, sep = "")

# Apply the function to remove non-digit characters
long_aedes_data$ID  <- sapply(long_aedes_data$ID, keep_digits)

```


```{r}

############################################################################################
# Mosquitoes: 2023: indication of places positive for presence of Aedes
############################################################################################

positive_aedes_2023 <- 
  long_aedes_data %>%
  filter(year == 2023 & presence == 1) 


# Join the count data with the spatial data
positive_aedes_2023_sf <- belgium_shp %>%
  inner_join(positive_aedes_2023, by = c("Postcode" = "Postcode"))


library(leaflet)

# Create the Leaflet map
leaflet_map <- leaflet(data = positive_aedes_2023_sf) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    fillColor = "red",  # Fill all polygons with red
    weight = .3,  # Increase the border weight
    opacity = 1,
    color = 'black',  # Border color set to black for contrast
    dashArray = '3',
    fillOpacity = 0.5,  # Adjust fill opacity for better visibility
    highlight = highlightOptions(
      weight = 5,
      color = "white",
      dashArray = "",
      fillOpacity = 1,
      bringToFront = TRUE
    ),
    label = ~paste("Municipality: ", Municipality, "; Postcode:", Postcode),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "10px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    colors = "red",  # Legend color set to red
    labels = "Positive",  # Label for legend
    opacity = 1,
    title = "Aedes presence",
    position = "bottomright"
  )

# Show the map
leaflet_map




```



```{r}

###############################################################################################################################
# Cumulative mosquitoes over the last 5 years: indication of places being once/twice/3x/4X or 5x positive for presence of Aedes albopictus
###############################################################################################################################

# Install necessary packages if not already installed
#install.packages(c("dplyr", "sf", "plotly"))

# Load the libraries
library(dplyr)
library(sf)


# Convert character field to numeric
long_aedes_data$year <- as.numeric(long_aedes_data$year)


# Extract unique years
unique_years <- unique(long_aedes_data$year)


# Order the years in descending order
unique_ordered_years <- sort(unique_years, decreasing = TRUE)

# Select the first 5 numbers
unique_ordered_years <- unique_ordered_years[1:5]


positive_aedes_counts_5y <- 
  long_aedes_data %>%
  filter(year %in% unique_ordered_years & detection == 1) %>%
  group_by(Postcode, Municipality) %>%
  summarise(count = n())

# Join the count data with the spatial data
positive_aedes_counts_5y_sf <- belgium_shp %>%
  inner_join(positive_aedes_counts_5y, by = c("Postcode" = "Postcode"))

# Replace NA counts with 0
positive_aedes_counts_5y_sf$count[is.na(positive_aedes_counts_5y_sf$count)] <- 0

```


```{r}


library(leaflet)

# Define color palette
color_palette <- colorNumeric(
  palette = c("yellow", "#ff0000"),  # Light red to full red
  domain = c(1, 5)  # Adjust domain to cover the range from 1 to 5
)

# Custom labels for the legend
legend_labels <- c("1", "2", "3", "4", "5")

# Create the Leaflet map
leaflet_map <- leaflet(data = positive_aedes_counts_5y_sf) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    fillColor = ~ifelse(count == 0, "white", color_palette(count)),  # Use white for 0
    weight = .3,  # Further increase the border weight
    opacity = .5,
    color = 'black',  # Change the border color to black for higher contrast
    dashArray = '3',
    fillOpacity = 1,  # Adjust fill opacity for better visibility
    highlight = highlightOptions(
      weight = 5,
      color = "white",
      dashArray = "",
      fillOpacity = 1,
      bringToFront = TRUE
    ),
    label = ~paste("Municipality: ", Municipality, "; Postcode:", Postcode, "Sightings in previous 5 years:", count),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "10px",
      direction = "auto"
    )
  ) %>%
  addLegend(
    colors = c(color_palette(c(1, 2, 3, 4, 5))),  # Custom colors for legend
    labels = legend_labels,
    opacity = 1,
    title = "Cumulative years",
    position = "bottomright"
  )

# Show the map
leaflet_map



```

Mosquitoes: 2023: indication of places positive for presence of aedes


```{r}

##########################################################
# Dengue 
##########################################################

library(readxl)

DENV_Belgium <- read_excel("data/DENV_Belgium.xlsx", 
     col_types = c("text", "text", "text", 
         "text",  "text", "text"))

# note there are problems with the data, doesn't match the full list, for now we will remove any values with letters and cut numbers over 4 digits


# Assuming your dataset is loaded as DENV_Belgium
# Replace spaces with underscores in column names

names(DENV_Belgium) <- gsub(" ", "_", names(DENV_Belgium))

# Check the new column names
names(DENV_Belgium)

DENV_Belgium <- dplyr::rename(DENV_Belgium, Postcode = "Postal_code")


DENV_Belgium <- DENV_Belgium %>% 
  mutate(Postcode = as.character(Postcode),  # Ensure text column is character type
         Postcode = str_extract(Postcode, "\\d{4}"),
         Postcode = as.numeric(Postcode))  # Convert Postcode to numeric

  


```



```{r}

# Load the tidyverse package
library(tidyverse)

# Assuming your dataset is loaded as DENV_Belgium
# Extract characters from Sample_ID to create Year and Month columns

# Assuming DENV_Belgium is your data frame and Sample_ID is a column in this data frame
DENV_Belgium <- DENV_Belgium %>%
  mutate(
    dengue_year = substr(Sample_ID, 1, 2),  # Extracts the first two characters
    Month = substr(Sample_ID, 3, 4)  # Extracts the third and fourth characters
  ) %>%
  mutate(
    dengue_year = paste0("20", dengue_year)  # Prefix "20" to the extracted year
  )

# View the updated dataset to check the new fields
print(head(DENV_Belgium))


```

```{r}


belgium_shp <- dplyr::left_join(belgium_shp, municipality_post_code_link, by = "Postcode")


```



```{r}

######################################################################################
# Identification of overlaps 2023: Dengue infections and 2023 Aedes 2023 detections
#######################################################################################

# Counting observations per year
yearly_postcode_dengue_counts <- DENV_Belgium %>%
  group_by(dengue_year, Postcode) %>%
  summarise(count = n()) %>%
  ungroup()

# first select year of dengue introduction
# Next query this against the aedes data set, it should only select the current years and up to 4 years before. results should be displayed in a map and table. 


# Define the target year
target_year <- 2023


yearly_postcode_dengue_counts$dengue_year <- as.numeric(yearly_postcode_dengue_counts$dengue_year)


denv_aedes_matches <- yearly_postcode_dengue_counts %>%
  filter(dengue_year == target_year) %>%
  inner_join(long_aedes_data, by = c("Postcode" = "Postcode", "dengue_year" = "year")) %>%
  filter(detection == 1)  
  

# note needs to be alert if cases not matched
denv_aedes_matched_cases_shp <- dplyr::right_join(belgium_shp, denv_aedes_matches, by = "Postcode") 
  


# Load necessary libraries
library(sf)
library(leaflet)

# Read your data into an SF object
# Replace 'your_data_file' with your actual data file path
# Example assuming your data is in a shapefile




# Create the bins
denv_aedes_matched_cases_shp$bins <- cut(denv_aedes_matched_cases_shp$count, breaks = c(0, 2,  5, 10, 20, 30, 50, Inf), 
                        labels = c("1-2", "3-5", "6-10", "11-20", "21-30", "31-50", ">50"), right = FALSE)

# Create a color palette based on the bins
pal <- colorFactor(palette = "YlOrRd", domain = denv_aedes_matched_cases_shp$bins)

# Create the leaflet map
map <- leaflet(denv_aedes_matched_cases_shp) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    fillColor = ~pal(bins),
    fillOpacity = 0.7,
    color = "#BDBDC3",
    weight = 1,
    popup = ~paste("Municipality: ", namedut,  "; Post Code:", Postcode,  "; Dengue Cases 2013:", count)
  ) %>%
  addLegend(
    pal = pal,
    values = ~bins,
    opacity = 0.7,
    title = "Dengue Cases",
    position = "bottomright"
  )

# Print the map
map



```



```{r}

######################################################################################
# Identification of overlaps 2023: Dengue infections and historical aedes detections
#######################################################################################

# Counting observations per year
yearly_postcode_dengue_counts <- DENV_Belgium %>%
  group_by(dengue_year, Postcode) %>%
  summarise(count = n()) %>%
  ungroup()

# first select year of dengue introduction
# Next query this against the aedes data set, it should only select the current years and up to 4 years before. results should be displayed in a map and table. 


# Define the target year
target_year <- 2023

# Calculate the range of years
start_year <- target_year - 5

year_list <- seq(from = start_year, to = target_year)

denv_aedes_matches <- yearly_postcode_dengue_counts %>%
  filter(dengue_year == target_year) %>%
  inner_join(long_aedes_data, by = "Postcode") %>%
  filter(year >= start_year & year <= target_year) %>%
  arrange(Postcode, desc(year))

# make centroids of cases - centroid bubbles in map, 
denv_aedes_matched_cases <- denv_aedes_matches %>%
  dplyr::select(-detection,  -`Site codes`,  -Site_type, -Status, -year, -Latitude,   -Longitude)  %>%
  group_by(count, dengue_year,   Municipality, Postcode) %>%
  summarise() %>% 
  ungroup()

# note needs to be alert if cases not matched
denv_aedes_matched_cases_shp <- dplyr::right_join(belgium_shp, denv_aedes_matched_cases, by = "Postcode") 
  
denv_aedes_matched_cases_centroids <- st_centroid(denv_aedes_matched_cases_shp)
# Extract coordinates and create longitude and latitude columns
denv_aedes_matched_cases_centroids <- denv_aedes_matched_cases_centroids %>%
  mutate(
    longitude = st_coordinates(.)[, 1],
    latitude = st_coordinates(.)[, 2]
  )

denv_aedes_matches_years_shp <- dplyr::right_join(belgium_shp, denv_aedes_matches, by = "Postcode")

denv_aedes_matches_years_shp <- dplyr::select(denv_aedes_matches_years_shp, -niscode,      -nameger,      -namefre,      -namedut,      -dengue_year,  -`Site codes`,  -Latitude,     -Longitude,    -Site_type)


# Calculate the maximum year in the dataset
max_year <- 2023

sf_data <- denv_aedes_matches_years_shp %>%
  group_by(geometry, Postcode, count, Municipality) %>%
  arrange(desc(year)) %>%
  summarise(recent_obs = first(year[detection == 1], default = NA)) 

denv_aedes_matched_cases_centroids <- denv_aedes_matched_cases_centroids %>%
  filter(!is.na(count))

library(leaflet)
library(RColorBrewer)
 

# Define color palette
color_palette <- colorNumeric(
  palette = c("yellow", "red"),  # Light red to full red
  domain = c(start_year, target_year)  # Adjust domain to cover the range from 1 to 5
)


# Create the Leaflet map
leaflet(sf_data) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    fillColor = ~color_palette(recent_obs),  # Correctly use the color palette
    weight = 1,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlightOptions = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = ~paste("Municipality: ", Municipality,  "; Postcode: ", Postcode,  "; Last Aedes Observation: ", recent_obs, "; Number of Dengue Cases: ", count), 
  ) %>%
  addLegend(
  pal = color_palette,  # Use the palette function directly
  values = year_list,  # Use the year list for legend values
  opacity = 1,
  title = "Last detection Yr",
  position = "bottomright", 
  labFormat = labelFormat(big.mark = "")
)



```





```{r}

#################################################################################################################
# Cumulative dengue cases over the last 5 years: - working with gradiation of colours to indicate number of cases
#################################################################################################################


# first select year of dengue introduction
# Next query this against the aedes data set, it should only select the current years and up to 5 years before. results should be displayed in a map and table. 


# Define the target year
target_year <- 2023

# Calculate the range of years
start_year <- target_year - 5

postcode_dengue_counts_5y <- yearly_postcode_dengue_counts %>%
  filter(dengue_year >= start_year & dengue_year <= target_year) %>%
  arrange(Postcode, desc(dengue_year))


postcode_dengue_counts_5y <- postcode_dengue_counts_5y %>%
  group_by(Postcode) %>%
  summarise(count=sum(count))

postcode_dengue_counts_5y$count <- as.numeric(postcode_dengue_counts_5y$count)

# note needs to be alert if cases not matched
postcode_dengue_counts_5y_shp <- dplyr::inner_join(belgium_shp, postcode_dengue_counts_5y, by = "Postcode") 
  

# Load necessary libraries
library(sf)
library(leaflet)

# Read your data into an SF object
# Replace 'your_data_file' with your actual data file path
# Example assuming your data is in a shapefile




# Create the bins
postcode_dengue_counts_5y_shp$bins <- cut(postcode_dengue_counts_5y_shp$count, breaks = c(0, 2,  5, 10, 20, 30, 50, Inf), 
                        labels = c("1-2", "3-5", "6-10", "11-20", "21-30", "31-50", ">50"), right = FALSE)

# Create a color palette based on the bins
pal <- colorFactor(palette = "YlOrRd", domain = postcode_dengue_counts_5y_shp$bins)

# Create the leaflet map
map <- leaflet(postcode_dengue_counts_5y_shp) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    fillColor = ~pal(bins),
    fillOpacity = 0.7,
    color = "#BDBDC3",
    weight = 1,
    popup = ~paste("Municipality: ", namedut,  "; Post Code:", Postcode,  "; Dengue Cases in past 5y:", count)
  ) %>%
  addLegend(
    pal = pal,
    values = ~bins,
    opacity = 0.7,
    title = "Dengue Cases",
    position = "bottomright"
  )

# Print the map
map



```


```{r}

####################################################################################
#  Dengue cases 2023: working with gradiation of colours to indicate number of cases
####################################################################################

# Define the target year
target_year <- 2023


postcode_dengue_counts_2023 <- yearly_postcode_dengue_counts %>%
  filter(dengue_year == target_year) 


postcode_dengue_counts_2023$count <- as.numeric(postcode_dengue_counts_2023$count)

# note needs to be alert if cases not matched
postcode_dengue_counts_2023_shp <- dplyr::inner_join(belgium_shp, postcode_dengue_counts_2023, by = "Postcode") 
  

# Load necessary libraries
library(sf)
library(leaflet)

# Read your data into an SF object
# Replace 'your_data_file' with your actual data file path
# Example assuming your data is in a shapefile


# Create the bins
postcode_dengue_counts_2023_shp$bins <- cut(postcode_dengue_counts_2023_shp$count, breaks = c(0, 2,  5, 10, 20, 30, 50, Inf),  
                        labels = c("1-2", "3-5", "6-10", "11-20", "21-30", "31-50", ">50"), right = FALSE)

# Create a color palette based on the bins
pal <- colorFactor(palette = "YlOrRd", domain = postcode_dengue_counts_2023_shp$bins)

# Create the leaflet map
map <- leaflet(postcode_dengue_counts_2023_shp) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    fillColor = ~pal(bins),
    fillOpacity = 0.7,
    color = "#BDBDC3",
    weight = 1,
    popup = ~paste("Municipality: ", namedut,  "; Post Code:", Postcode,  "; Dengue Cases 2023:", count)
  ) %>%
  addLegend(
    pal = pal,
    values = ~bins,
    opacity = 0.7,
    title = "Cases",
    position = "bottomright"
  )

# Print the map
map



```



```{r}

###############################################################################################################################
# Cumulative mosquitoes over the last 5 years in places which have been positive at least once in the past 5 years
###############################################################################################################################

# Install necessary packages if not already installed
#install.packages(c("dplyr", "sf", "plotly"))

# Load the libraries
library(dplyr)
library(sf)



# Convert character field to numeric
long_aedes_data$year <- as.numeric(long_aedes_data$year)


# Extract unique years
unique_years <- unique(long_aedes_data$year)


# Order the years in descending order
unique_ordered_years <- sort(unique_years, decreasing = TRUE)

# Select the first 5 numbers
unique_ordered_years <- unique_ordered_years[1:5]

positive_aedes_counts_5y <- 
  long_aedes_data %>%
  filter(year %in% unique_ordered_years & detection == 1) %>%
  group_by(Postcode, Municipality) %>%
  summarise(count = n())


# Replace NA counts with 0
positive_aedes_counts_5y$count[is.na(positive_aedes_counts_5y$count)] <- 0



# first select year of dengue introduction
# Next query this against the aedes data set, it should only select the current years and up to 5 years before. results should be displayed in a map and table. 


# Define the target year
target_year <- 2023

# Calculate the range of years
start_year <- target_year - 5

postcode_dengue_counts_5y <- yearly_postcode_dengue_counts %>%
  filter(dengue_year >= start_year & dengue_year <= target_year) %>%
  arrange(Postcode, desc(dengue_year))


postcode_dengue_counts_5y <- postcode_dengue_counts_5y %>%
  group_by(Postcode) %>%
  summarise(count=sum(count))

postcode_dengue_counts_5y$count <- as.numeric(postcode_dengue_counts_5y$count)


postcode_dengue_counts_5y <- dplyr::rename(postcode_dengue_counts_5y, "dengue_cases" = count)

positive_aedes_counts_5y <- dplyr::rename(positive_aedes_counts_5y, "Aedes_obs_5y" = count)

aedes_dengue_counts_5y <- dplyr::inner_join(postcode_dengue_counts_5y, positive_aedes_counts_5y, by = "Postcode")

# note needs to be alert if cases not matched
aedes_dengue_counts_5y_shp <- dplyr::inner_join(belgium_shp, aedes_dengue_counts_5y, by = "Postcode") 



# Number of cases in 5 years where there has been at least one sighting of Aedes albopictus in previous 5 years

# Load necessary libraries
library(sf)
library(leaflet)

# Read your data into an SF object
# Replace 'your_data_file' with your actual data file path
# Example assuming your data is in a shapefile


# Create the bins
aedes_dengue_counts_5y_shp$bins <- cut(aedes_dengue_counts_5y_shp$dengue_cases, breaks = c(0, 2, 5, 10, 20, 30, 50, Inf), 
                        labels = c("1-2", "3-5", "6-10", "11-20", "21-30", "31-50", ">50"), right = FALSE)

# Create a color palette based on the bins
pal <- colorFactor(palette = "YlOrRd", domain = aedes_dengue_counts_5y_shp$bins)

# Create the leaflet map
map <- leaflet(aedes_dengue_counts_5y_shp) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    fillColor = ~pal(bins),
    fillOpacity = 0.7,
    color = "#BDBDC3",
    weight = 1,
    popup = ~paste("Municipality: ", namedut,  "; Post Code:", Postcode,  "; Dengue Cases:", dengue_cases)
  ) %>%
  addLegend(
    pal = pal,
    values = ~bins,
    opacity = 0.7,
    title = "Cases",
    position = "bottomright"
  )

# Print the map
map


```
  


```{r}


############################################################################################################
# Number of cumulative dengue cases over past 5 years where there was a direct overlap with Aedes Albopictus
############################################################################################################


# Install necessary packages if not already installed
#install.packages(c("dplyr", "sf", "plotly"))

# Load the libraries
library(dplyr)
library(sf)



# Convert character field to numeric
long_aedes_data$year <- as.numeric(long_aedes_data$year)

positive_aedes_counts <- 
  long_aedes_data %>%
  dplyr::select(Postcode, Municipality, year, detection) %>%
  filter(detection == 1) %>%
  group_by(Postcode, Municipality, year) %>%
  summarise(count = n())


# Define the target year
target_year <- 2023

# Calculate the range of years
start_year <- target_year - 5

postcode_dengue_counts_5y <- yearly_postcode_dengue_counts %>%
  filter(dengue_year >= start_year & dengue_year <= target_year) %>%
  arrange(Postcode, desc(dengue_year)) %>%
  dplyr::rename(year = "dengue_year")



postcode_dengue_counts_5y <- dplyr::rename(postcode_dengue_counts_5y, "dengue_cases" = count)

positive_aedes_counts <- dplyr::rename(positive_aedes_counts, "Aedes_obs_5y" = count)

postcode_dengue_counts_5y$year <- as.numeric(postcode_dengue_counts_5y$year)

annual_aedes_dengue_counts_5y <- dplyr::inner_join(postcode_dengue_counts_5y, positive_aedes_counts, by = c("Postcode", "year"))

# make sure there are no repeats in the data set
annual_aedes_dengue_counts_5y <- annual_aedes_dengue_counts_5y %>%
  group_by(Postcode) %>%
  summarise(dengue_cases=sum(dengue_cases)) %>%
  ungroup()


# note needs to be alert if cases not matched
annual_aedes_dengue_counts_5y_shp <- dplyr::inner_join(belgium_shp, annual_aedes_dengue_counts_5y, by = "Postcode") 


# Load necessary libraries
library(sf)
library(leaflet)

# Read your data into an SF object
# Replace 'your_data_file' with your actual data file path
# Example assuming your data is in a shapefile


# Create the bins
annual_aedes_dengue_counts_5y_shp$bins <- cut(annual_aedes_dengue_counts_5y_shp$dengue_cases, breaks = c(0, 3, 5, 10, 20, 30, 50, Inf), 
                        labels = c("1-2", "3-5", "6-10", "11-20", "21-30", "31-50", ">50"), right = FALSE)

# Create a color palette based on the bins
pal <- colorFactor(palette = "YlOrRd", domain = annual_aedes_dengue_counts_5y_shp$bins)

# Create the leaflet map
map <- leaflet(annual_aedes_dengue_counts_5y_shp) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    fillColor = ~pal(bins),
    fillOpacity = 1,
    color = "#BDBDC3",
    weight = 1,
    popup = ~paste("Municipality: ", namedut,  "; Post Code:", Postcode,  "; Dengue Cases:", dengue_cases)
  ) %>%
  addLegend(
    pal = pal,
    values = ~bins,
    opacity = 1,
    title = "Cases",
    position = "bottomright"
  )

# Print the map
map


```



```{r}

# Define the target year

may <- 05
october <- 10


# Calculate the range of years
start_year <- target_year - 5

# Counting observations per year
yearly_postcode_dengue_counts_may_oct <- DENV_Belgium %>%
  group_by(dengue_year) %>%
  arrange(dengue_year, Month) %>%
  filter(Month >= may & Month <= october)
  



summarise(count = n()) %>%
  ungroup()
  

dplyr::group_by(Postcode Sub_region  dengue_year Month)



```

















DENGUE CASE DATA

The figure with origen of travels for the cases between may-october of the last 5 years


```{r}

# Counting observations per year
yearly_dengue_counts <- DENV_Belgium %>%
  group_by(dengue_year) %>%
  summarise(count = n())

# Look at year trends

library(plotly)
library(dplyr)

# Creating the bar chart
fig <- plot_ly(data = yearly_dengue_counts, x = ~dengue_year, y = ~count, type = 'bar',
               marker = list(color = 'rgba(50, 171, 96, 0.6)',
                             line = list(color = 'rgba(50, 171, 96, 1.0)', width = 1.5)))
fig <- fig %>% layout(title = 'Observations per Year',
                      xaxis = list(title = 'Year'),
                      yaxis = list(title = 'Number of Observations'))
fig



```

```{r}

# Look at distribution of cases by month, select each year
# Filter data for the year 2020
monthly_data <- DENV_Belgium %>%
  filter(dengue_year == 2023)

# Counting observations per month
monthly_counts <- monthly_data %>%
  group_by(Month) %>%
  summarise(count = n())


# Creating the bar chart
fig <- plot_ly(data = monthly_counts, x = ~Month, y = ~count, type = 'bar',
               marker = list(color = 'rgba(55, 128, 191, 0.7)',
                             line = list(color = 'rgba(55, 128, 191, 1.0)', width = 1.5)))
fig <- fig %>% layout(title = 'Monthly Observations for the Year 2020',
                      xaxis = list(title = 'Month', tickmode = "array", tickvals = 1:12, ticktext = month.name),
                      yaxis = list(title = 'Number of Observations'))
fig



```

```{r}


# Pie chart, select main countries per all of Belgium, perhaps we could also look at municipalities etc.  

# look at main source locations

library(dplyr)

# Counting observations per country
country_counts <- DENV_Belgium %>%
  group_by(Sub_region) %>%
  summarise(count = n()) %>%
  mutate(percentage = count / sum(count) * 100)

library(plotly)

# Creating the pie chart
fig <- plot_ly(country_counts, labels = ~Sub_region, values = ~percentage, type = 'pie',
               textinfo = 'label+percent',
               insidetextorientation = 'radial')

fig <- fig %>% layout(title = 'Percentage of Observations Per Sub-region')
fig

```

